// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzvonrpyefweapxftanj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6dm9ucnB5ZWZ3ZWFweGZ0YW5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg4MjAwNjQsImV4cCI6MjA1NDM5NjA2NH0.E0iTTch0A09dQIOuG58a7JZ5g50tfdMr7bEDOflz29I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);